apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
  labels:
    app: python-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
        - name: python-application
          image: manalitekawade0804/python-application:latest  # Update with your Docker image
          ports:
            - containerPort: 5000  # The port your application listens on

