apiVersion: v1
kind: Service
metadata:
  name: python-application-service
spec:
  type: NodePort
  selector:
    app: python-application
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30001  # NodePort range is typically 30000-32767
