apiVersion: v1
kind: Service
metadata:
  name: python-application
spec:
  type: NodePort  # Expose the service externally
  selector:
    app: python-application
  ports:
    - port: 5000         # Port that the service will expose
      targetPort: 5000   # Port that the container listens on
